### ISSUE TITLE
Erratic behavior of at least temperature and humidity from integration

### ISSUE THREAD

**Issue by finity69x2** [firstof9/ha-nws#7]
I've been using this integration for a long time now for the forecast information to feed it to weather card.

However, I've always had a problem with the temp & humidity entities being very erratic in what was reported. So much so that I've never used them for any purpose.

I always thought it was just the NWS webserver reporting bad information for my local airport. But I just recently created a scrape sensor pulling info directly from the website and it has been fairly solid and accurate.

So I decided to test this integration by removing it and using the built-in NWS integration instead. The difference was very stark.

here is what your integration shows for temp & humidity compared to the other integrations (yours is the the orange graph):

![ha-nws example scrubbed](https://user-images.githubusercontent.com/32221243/148472004-ce93ddb9-29ac-440c-9ea1-12239329a2bb.jpg)

here is after 12 hours after reverting back to the built-in NWS integration (still the orange for both):

![ha-nws example-2](https://user-images.githubusercontent.com/32221243/148472357-43adf290-9e0d-4507-8e0e-37942593c805.jpg)

And after 23 hours (orange is still there but the built-in integration has pretty much the same results as the rest at this point so it's harder to see):

![ha-nws example-3](https://user-images.githubusercontent.com/32221243/148472389-bcb0f020-7568-477e-b7f1-e8ec69293313.jpg)

I also just looked at pressure and shows the same erratic behavior.

Do you have any idea why your integration would be so wildly erratic compared to the others, especially the built-in one that should essentially be the same aside from the extra forecast data supplied by yours?

Could it be a difference in the way yours handles errors from an invalid response from the NWS API?

**Comment by firstof9** [comment]
I'll have a look and see if I need to rebase on the core component, the only changes I make are to combine the lows and the highs in the forecast and add that little forecast text from the NWS API. Everything else should be exactly the same. :man_shrugging:

**Comment by firstof9** [comment]
Looks like it was an old library since NWS had changed their API ever so slightly.

**Comment by firstof9** [comment]
`1.0.2` should fix this, I verified it on my dev instance.

**Comment by finity69x2** [comment]
I just installed the update. It will be a while before I can tell if it's better.

**Comment by finity69x2** [comment]
Now there is another problem...

none of the usual entities are now available:

![image](https://user-images.githubusercontent.com/32221243/148593031-040e48b0-a9d0-45ae-8c6f-032371f6783b.png)
and is reflected in the weather card

the only one available is the weather.daynight entity which has no forecast data.

![image](https://user-images.githubusercontent.com/32221243/148593315-f2c1e236-d321-499e-ba2e-5e5275a29bad.png)

**Comment by elwing00** [comment]
I've been having issues with the servers/API not responding and thus not having the forecast available to use.  But, I do currently have all entities showing for KAGC.  Check your logs to see if the API is acting up (again)

**Comment by firstof9** [comment]
I was just about to ask about errors in the log. :+1: 

This is how my temperature sensor is reporting now.
![image](https://user-images.githubusercontent.com/1105672/148594540-4813fb66-f395-484c-9f17-77f2bf377bb8.png)

EDIT: @finity69x2 those other sensors are disabled, but I am getting a forecast.
![image](https://user-images.githubusercontent.com/1105672/148595198-c754cbf0-4bc7-438f-9c7e-9ee83955e83b.png)

**Comment by finity69x2** [comment]
I don't get any forecast and it doesn't show up the attributes of the weather entity either.

![image](https://user-images.githubusercontent.com/32221243/148596161-c52481f0-4b87-4d4f-9653-3be33dc13e32.png)

So I guess I don't know where the forecast comes from if those other sensors are disabled?

no errors in the log at all.

**Comment by elwing00** [comment]
That's the exact issue I get when I get an Internal Server Error from the NWS API servers
<img width="1129" alt="Screen Shot 2022-01-07 at 2 28 29 PM" src="https://user-images.githubusercontent.com/56235263/148596805-75065cfe-7f90-42d5-b797-3be73091b974.png">

It should look like this

**Comment by finity69x2** [comment]
OT, but it's funny to see the difference between the midwest and southwest (brrr and sweat) LOL.

**Comment by firstof9** [comment]
Dude 50s and 60s are cold :cold_face:

**Comment by elwing00** [comment]
The forecast is a separate API call it seems (https://api.weather.gov/gridpoints/PBZ/78,60/forecast for me), and that has been failing a lot for me lately (I'd say in the last 2-3 weeks)

**Comment by firstof9** [comment]
My weather entity data:
```yaml
temperature: 61
humidity: 45
pressure: 29.96
wind_bearing: 90
wind_speed: 8
visibility: 10
forecast:
  - detailed_description: >-
      Sunny. High near 69, with temperatures falling to around 67 in the
      afternoon. East southeast wind 0 to 5 mph. Tonight, Partly cloudy. Low
      around 48, with temperatures rising to around 50 overnight. North
      northeast wind 0 to 5 mph.
    temperature: 69
    datetime: '2022-01-07T12:00:00-07:00'
    daytime: true
    condition: sunny
    precipitation_probability: 0
    wind_bearing: 112.5
    wind_speed: 2
    templow: 48
  - detailed_description: >-
      Partly sunny, with a high near 66. Northeast wind 0 to 5 mph. Tonight,
      Partly cloudy, with a low around 48. North northeast wind 0 to 5 mph.
    temperature: 66
    datetime: '2022-01-08T06:00:00-07:00'
    daytime: true
    condition: cloudy
    precipitation_probability: 0
    wind_bearing: 45
    wind_speed: 2
    templow: 48
...
```

Really looking like maybe the API is having issues for your location @finity69x2 or the library's acting up. I'm leaning towards the API being weird for your location.

Try setting the logging for `pynws` to debug.

```yaml
service: logger.set_level
data:
  pynws: debug
```

should do the trick.
